# Generated by Django 5.2.8 on 2025-12-01 23:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Etiketler',
            },
        ),
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Türler',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('ozet', models.TextField()),
                ('yayin_tarihi', models.DateField()),
                ('yonetmen', models.CharField(max_length=100)),
                ('etiketler', models.ManyToManyField(related_name='filmler', to='filmler.etiket')),
                ('turler', models.ManyToManyField(related_name='filmler', to='filmler.tur')),
            ],
        ),
        migrations.CreateModel(
            name='Puanlama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.IntegerField(help_text='Lütfen 1 ile 10 arasında bir puan giriniz.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmler.film')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Puanlamalar',
                'unique_together': {('kullanici', 'film')},
            },
        ),
    ]
