# Generated by Django 5.2.8 on 2025-12-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etiket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='puanlama',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tur',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='puanlama',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='film',
            name='afis_url',
            field=models.CharField(blank=True, help_text='Afiş resminin linki', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='etiket',
            name='isim',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='baslik',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='etiketler',
            field=models.ManyToManyField(to='filmler.etiket'),
        ),
        migrations.AlterField(
            model_name='film',
            name='turler',
            field=models.ManyToManyField(to='filmler.tur'),
        ),
        migrations.AlterField(
            model_name='puanlama',
            name='puan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tur',
            name='isim',
            field=models.CharField(max_length=50),
        ),
    ]
